# Generated by Django 6.0.5 on 2026-06-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_product_location_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('laptops', 'Laptops'), ('cameras', 'Cameras'), ('gaming', 'Gaming'), ('drones', 'Drones'), ('bikes', 'Bikes'), ('cars', 'Cars'), ('furniture', 'Furniture'), ('tools', 'Tools'), ('books', 'Books'), ('musical_instruments', 'Music'), ('projectors', 'Projectors'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
